import type { NextPage } from "next";
import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import { Playground } from "../components/playground";
import styles from "../styles/Home.module.css";
import { Wallet } from "../components/wallet";
import { Nav } from "../components/nav";
import { Footer } from "../components/footer";
import { Button } from "../components/button";
import { useAppContext } from "../components/context";

const Create: NextPage = () => {
    const [name, setName] = React.useState<string>("");
    const [bpm, setBpm] = React.useState<string>("");
    const [rawSongNotes, setRawSongNotes] = React.useState<string>("");
    const context = useAppContext();

    const updateSongCallback = (notes: string) => {
        //callback passed into the Playground to get the music notes
        setRawSongNotes(notes);
    };

    const createNewSong = async () => {
        const provider = context.provider;
        const signer = context.signer;
        const contract = context.contract;
        if (provider && signer && contract) {
            const contractWithSigner = contract.connect(signer);

            let res;

            if (rawSongNotes.length !== 0) {
                res = await contractWithSigner.createSongWithNotes(name, bpm, rawSongNotes.split(""));
            } else {
                res = await contractWithSigner.createNewSong(name, bpm);
            }

            console.log("executed create new song: ", res);
        } else {
            console.error("Could not verify provider or signer or contract");
        }
    };

    const numericBpm = parseInt(bpm) ? parseInt(bpm) : 110;
    return (
        <div className={styles.container}>
            <Head>
                <title>Thalia</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Nav />
            <main className={styles.main}>
                <div className="py-4">
                    <h1 className="text-xl font-bold">It's only you and the music.</h1>
                    <p className="text-s opacity-70">
                        Create a song.<br></br>Write some notes.<br></br>Commit them to the blockchain.<br></br>Now
                        anyone can add to this song.<br></br>I can't wait to see to what you create.
                    </p>
                </div>
                <div className="flex flex-col">
                    <input
                        className="text-s py-4"
                        placeholder={"Name?"}
                        value={name}
                        onChange={(evt) => setName(evt.target.value)}
                    />
                    <input
                        className="text-s py-4"
                        placeholder={"Beats Per Minute? Larger number = faster music"}
                        value={bpm}
                        onChange={(evt) => setBpm(evt.target.value)}
                    />
                </div>
                <Playground
                    prevMusicNotes={""}
                    rawNotes={rawSongNotes}
                    updateSongCallback={updateSongCallback}
                    bpm={numericBpm}
                />
                <Button onClick={createNewSong}>Create</Button>
                <Footer />
            </main>
        </div>
    );
};

export default Create;
