import type { NextPage } from "next";
import * as React from "react";
import Head from "next/head";
import { Playground } from "../components/playground";
import styles from "../styles/Home.module.css";
import { Nav } from "../components/nav";
import { Footer } from "../components/footer";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Thalia</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Nav />
            <main className={styles.main}>
                <div className="py-4">
                    <h1 className="text-xl font-bold">Thalia.</h1>
                    <p className="text-xs opacity-50">A piano for the people, by the people.</p>
                </div>
                <p className="opacity">
                    <strong>On-chain music composition</strong>.<br></br>Compose tunes with anyone and everyone{" "}
                    <strong>straight from your keyboard</strong>.
                </p>
                <Playground bpm={140} />
                <Footer />
            </main>
        </div>
    );
};

export default Home;
