import type { NextPage } from "next";
import * as React from "react";
import Head from "next/head";
import { Playground } from "../components/playground";
import styles from "../styles/Home.module.css";
import { Nav } from "../components/nav";

const FindTune: NextPage = () => {
    const [searchValue, setSearchValue] = React.useState<string>("");

    return (
        <div className={styles.container}>
            <Head>
                <title>Thalia</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Nav />
            <main className={styles.main}>
                <h1 className="text-xl">Fine Tune</h1>
                <input
                    value={searchValue}
                    placeholder="Search for a song by name"
                    onChange={(evt) => setSearchValue(evt.target.value)}
                />
                <Playground />
            </main>
        </div>
    );
};

export default FindTune;
